name: Create Archive and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create and compress folders
        run: |
          shopt -s nullglob
          folders=("y2s1" "y2s2" "y3s1" "y3s2")
          for folder in "${folders[@]}"; do
            for dir in "$folder"/*/; do
              echo "Found directory: $dir"
              parent_dir=$(dirname "$dir")
              base_dir=$(basename "$dir")
              zip_name="${parent_dir}_${base_dir// /}.zip"
              zip -r "$zip_name" "$dir"/*
            done
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0
          release_name: Release v1.0
          draft: false
          prerelease: false

      - name: Find Archives
        run: |
          archives=$(ls ./*.zip)
          echo "::set-output name=archives::$archives"

      - name: Upload Archives to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: https://uploads.github.com/repos/JavaZeroo/DLI-BSc-Mathematics-Documents/releases/103722449/assets{?name,label}
          asset_path: ${{ steps.FindArchives.outputs.archives }}
          asset_name: 5_${{ env.FOLDER }}.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FOLDER: ${{ env.FOLDER }}
